version: "3.9"
services:
  servicename:
    build: ./LoadBalancer
    image: lb_image
    container_name: lb_server
    platform: "linux/x86_64"
    ports:
      - "5001:5000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/rajkiran/dsproj/DS_ASSIGNMENT_1/shardsinfo:/home/rajkiran/dsproj/DS_ASSIGNMENT_1/shardsinfo
    networks:
      net1:
        aliases:
          - lb_server
    environment:
      SERVER_ID: 100

  serviceshardmanager:
    build: ./ShardManager
    image: shardmanager_img
    container_name: shardmanager
    platform: "linux/x86_64"
    ports:
      - "5002:5000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net1:
        aliases:
          - shardmanager
    environment:
      SERVER_ID: 200

networks:
  net1:
    driver: bridge
